### ISSUE TITLE
3rd and 4th list item is always hidden

### ISSUE THREAD

**Issue by Xaero252** [npxtune/hide-nitro-css#13]
Pretty simple issue, really - if you have a list in a message, unordered or ordered, the third item is hidden by these two CSS selectors:
`#app-mount > div.appAsidePanelWrapper_bd26cc > div.notAppAsidePanel_bd26cc > div.app_bd26cc > div > div.layers_d4b6c5.layers_a01fb1 > div > div > div > div > div > nav > div.scroller_c47fa9.thin_eed6a8.scrollerBase_eed6a8.fade_eed6a8 > ul > li:nth-child(3), li:nth-child(3)`
`#app-mount > div.appAsidePanelWrapper_bd26cc > div.notAppAsidePanel_bd26cc > div.app_bd26cc > div > div.layers_d4b6c5.layers_a01fb1 > div > div > div > div > div > nav > div.scroller_c47fa9.thin_eed6a8.scrollerBase_eed6a8.fade_eed6a8 > ul > li:nth-child(3), li:nth-child(4)`

Both of these are actually two selectors - the comma doesn't inherit the specifity of the prior long chain, so it applies to *all* li which are the 3rd and 4th child, respectively: `, li:nth-child(3)` and `, li:nth-child(4)` apply globally across the entire DOM.

I don't see these elements in the DOM on my client on the friends list, but I think the first selector is probably also more complex than it needs to be. Likely it could be addressed with just:

```css
div.scroller_c47fa9.thin_eed6a8.scrollerBase_eed6a8.fade_eed6a8 > ul > li:nth-child(3),
div.scroller_c47fa9.thin_eed6a8.scrollerBase_eed6a8.fade_eed6a8 > ul > li:nth-child(4) {
    display: none;
}
```

To replace the first two rules for hiding that element. This reduces the complexity of the browser lookup. It can probably be reduced further - though for just two elements the performance impact is probably negligible.
